[package]
name = "apcBatteryRemainingNotify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snmp = "0.2.2"
clap = { version = "4.3.21", features = ["derive"] }
winrt-notification = "0.5.1"
